name: Boards Test

# The workflow will run on schedule and labeled pull requests
on:
  pull_request:

env:
  # It's convenient to set variables for values used multiple times in the workflow
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  find-boards:
    runs-on: ubuntu-latest

    outputs:
      fqbns: ${{ env.FQBNS }}

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup jq
        uses: dcarbone/install-jq-action@v1.0.1

      - name: Get board name
        run: 
          bash .github/scripts/find_new_boards.sh ${{ github.repository }} ${{github.event.number}}

  test-boards:
    needs: find-boards
    runs-on: ubuntu-latest
    if: needs.find-boards.outputs.fqbns != ''

    env:
      REPOSITORY: |
        - source-path: '.'
          name: "espressif:esp32"

    strategy:
      matrix: ${{ fromJson(needs.find-boards.outputs.fqbns) }}

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile sketch
        uses: P-R-O-C-H-Y/compile-sketches@main
        with:
          platforms: |
            ${{ env.REPOSITORY }}
          fqbn: ${{ matrix.fqbn }}
          use-json-file: false
          enable-deltas-report: false
          enable-warnings-report: false
          cli-compile-flags: |
            - --warnings="all"
          exit-on-fail: true
          sketch-paths:
            "- ./libraries/ESP32/examples/CI/CIBoardsTest/CIBoardsTest.ino"
